POST  http://localhost:4000/graphql
Content-Type: application/json
X-Request-Type: GraphQL

mutation deleteUserById($id: String!) {
  deleteUserById(id: $id) {
    id
    firstName
    lastName
  }
}

{"id":"3233c20a-e426-42cb-bfb8-d01f7fb3b576"}
